name: SSH
description: Configure SSH
inputs:
  name:
    description: SSH name
    required: false
    default: deploy
  host:
    description: HostName
    required: true
  user:
    description: Username
    required: true
  key:
    description: Private key
    required: true
outputs:
  name:
    description: SSH name
    value: ${{ steps.output.outputs.name }}
runs:
  using: composite
  steps:
    - name: Configure SSH
      env:
        NAME: inputs.name
        TEST: ${{ inputs.name }}
        HOST: inputs.host
        USER: inputs.user
        KEY: inputs.key
      # run: |
      #   mkdir -p ~/.ssh/
      #   echo "$KEY" > ~/.ssh/$NAME.key
      #   chmod 600 ~/.ssh/$NAME.key
      #   cat >>~/.ssh/config <<END
      #   Host $NAME
      #     HostName $HOST
      #     User $USER
      #     IdentityFile ~/.ssh/$NAME.key
      #     StrictHostKeyChecking no
      #   END
      #   echo "name='$NAME'" >> $GITHUB_OUTPUT
      run: echo name=$NAME test=$TEST
      run: echo "name='$NAME'" >> $GITHUB_OUTPUT
      shell: bash
