name: SSH
description: Configure SSH
inputs:
  host:
    description: HostName
    required: true
  user:
    description: Username
    required: true
  key:
    description: Private key
    required: true
  runs:
    using: composite
    steps:
      - name: Configure SSH
        env:
          HOST: inputs.host
          USER: inputs.user
          KEY: inputs.key
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/deploy.key
          chmod 600 ~/.ssh/deploy.key
          cat >>~/.ssh/config <<END
          Host deploy
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/deploy.key
            StrictHostKeyChecking no
          END
        shell: bash
