name: SSH
description: Configure SSH
inputs:
  identity:
    description: Identity
    required: false
    default: deploy
  host:
    description: Host name
    required: true
  user:
    description: User name
    required: true
  key:
    description: Private key
    required: true
  port:
    description: Port
    required: false
    default: 22
outputs:
  identity:
    description: Identity
    value: ${{ steps.config.outputs.identity }}
runs:
  using: composite
  steps:
    - name: Configure SSH
      id: config
      env:
        HOST: ${{ inputs.host }}
        USER: ${{ inputs.user }}
        KEY: ${{ inputs.key }}
        PORT: ${{ inputs.port }}
        IDENTITY: ${{ inputs.identity }}
      run: |
        mkdir -p ~/.ssh/
        echo "$KEY" > ~/.ssh/$IDENTITY.key
        chmod 600 ~/.ssh/$IDENTITY.key
        cat >>~/.ssh/config <<END
        Host $IDENTITY
          HostName $HOST
          User $USER
          Port $PORT
          IdentityFile ~/.ssh/$IDENTITY.key
          StrictHostKeyChecking no
        END
        echo "identity='$IDENTITY'" >> $GITHUB_OUTPUT
      shell: bash
