name: SSH
description: Configure SSH
inputs:
  # name:
  #   description: SSH name
  #   required: false
  #   default: deploy
  host:
    description: HostName
    required: true
  user:
    description: Username
    required: true
  key:
    description: Private key
    required: true
# outputs:
#   name:
#     description: SSH name
#     value: ${{ steps.output.outputs.name }}
runs:
  using: composite
  steps:
    - name: Configure SSH
      env:
        HOST: ${{ inputs.host }}
        USER: ${{ inputs.user }}
        KEY: ${{ inputs.key }}
      run: |
        mkdir -p ~/.ssh/
        echo "$KEY" > ~/.ssh/deploy.key
        chmod 600 ~/.ssh/deploy.key
        cat >>~/.ssh/config <<END
        Host deploy
          HostName $HOST
          User $USER
          IdentityFile ~/.ssh/deploy.key
          StrictHostKeyChecking no
        END
      shell: bash
    # - name: Output SSH name
      # run: echo "name='$NAME'" >> $GITHUB_OUTPUT
