name: Test
on: workflow_dispatch
jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Start server
        run: sudo docker compose up -d --build
      # - name: Install composer dependencies
      #   run: sudo docker exec -t gh-actions-docker-tests-php-1 sh -c 'composer install'
      # - name: Run PHPUnit tests
      #   run: sudo docker exec -t gh-actions-docker-tests-php-1 sh -c 'php bin/phpunit --testdox'
      - name: Check files
        run: |
          cd srv/app
          ls
  